package dev.aegisac.common.packet;
public enum PacketKind {
    MOVEMENT, TIMING, ENTITY_INTERACTION, DIGGING, PLACEMENT, USE_ITEM, HELD_ITEM,
    INVENTORY, ENTITY_ACTION, ABILITIES, VEHICLE, TELEPORT, VELOCITY, EXPLOSION,
    EFFECT, ENTITY_STATUS, BLOCK_ACKNOWLEDGEMENT, SWING, CLIENT_STATUS, WORLD_RESET, WORLD_CHANGE,
    INPUT, PAYLOAD, ENTITY_TRACKING, OTHER
}
