package dev.aegisac.common.physics;
/** A missing model/input is not cheat evidence. */
public enum Uncertainty {
    NO_WORLD, INVALIDATED_WORLD, STALE_WORLD, FUTURE_WORLD, OUTSIDE_SNAPSHOT, SCAN_BUDGET,
    REGION_NOT_OWNED, UNLOADED_CHUNK, UNSUPPORTED_VERSION, TRANSLATED_GEOMETRY, UNACKNOWLEDGED_WORLD,
    BEDROCK_PHYSICS_UNAVAILABLE, UNKNOWN_EDITION, INPUT_INFERRED, BASELINE_MISSING, PACKET_GAP, TELEPORT, VELOCITY_TIMING,
    ENTITY_COLLISION, INITIAL_OVERLAP, PISTON, ELYTRA, VEHICLE, RIPTIDE, FLIGHT, UNSUPPORTED_POSE,
    FLUID_FLOW, CLIMBABLE, COBWEB, HONEY, SLIME, SOUL_SAND, BUBBLE_COLUMN, SCAFFOLDING,
    SPECIAL_BLOCK, UNSUPPORTED_EFFECT, UNSUPPORTED_ATTRIBUTE, SNEAK_EDGE, STEP_MODEL,
    INVALID_MOVEMENT, CAPTURE_FAILED, DISABLED
}
